<Project Sdk="Dalamud.NET.Sdk/15.0.0">
    <PropertyGroup>
        <Version>0.10</Version>
        <OutputPath>dist</OutputPath>
        <PathMap Condition="$(SolutionDir) != ''">$(SolutionDir)=X:\</PathMap>
        <Platforms>x64</Platforms>
        <NoWarn>NU1510</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Questionable.Model\Questionable.Model.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="ECommons" Version="3.2.1.18" />
        <PackageReference Include="Pictomancy" Version="1.0.10" />
        <PackageReference Include="System.Net.Http" Version="4.3.4" />
        <PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
    </ItemGroup>
    
    <ItemGroup>
        <EmbeddedResource Include="world_locations.json">
            <LogicalName>GatheringPathRenderer.GBRWorldLocations</LogicalName>
        </EmbeddedResource>
    </ItemGroup>

</Project>
