<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0-windows7.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>14</LangVersion>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
        <Platforms>x64</Platforms>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.13.0" />
        <PackageReference Include="NSubstitute" Version="5.3.0" />
        <PackageReference Include="xunit" Version="2.9.3" />
        <PackageReference Include="xunit.runner.visualstudio" Version="3.1.3">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="coverlet.collector" Version="6.0.4">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Questionable\Questionable.csproj" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="..\QuestPaths\2.x - A Realm Reborn\**\*.json">
            <LogicalName>$([System.String]::new('%(RelativeDir)').Substring(3).Replace('\','/'))%(FileName)%(Extension)</LogicalName>
        </EmbeddedResource>
        <EmbeddedResource Include="..\QuestPaths\3.x - Heavensward\**\*.json">
            <LogicalName>$([System.String]::new('%(RelativeDir)').Substring(3).Replace('\','/'))%(FileName)%(Extension)</LogicalName>
        </EmbeddedResource>
        <EmbeddedResource Include="..\QuestPaths\4.x - Stormblood\**\*.json">
            <LogicalName>$([System.String]::new('%(RelativeDir)').Substring(3).Replace('\','/'))%(FileName)%(Extension)</LogicalName>
        </EmbeddedResource>
        <EmbeddedResource Include="..\QuestPaths\5.x - Shadowbringers\**\*.json">
            <LogicalName>$([System.String]::new('%(RelativeDir)').Substring(3).Replace('\','/'))%(FileName)%(Extension)</LogicalName>
        </EmbeddedResource>
        <EmbeddedResource Include="..\QuestPaths\6.x - Endwalker\**\*.json">
            <LogicalName>$([System.String]::new('%(RelativeDir)').Substring(3).Replace('\','/'))%(FileName)%(Extension)</LogicalName>
        </EmbeddedResource>
        <EmbeddedResource Include="..\QuestPaths\7.x - Dawntrail\**\*.json">
            <LogicalName>$([System.String]::new('%(RelativeDir)').Substring(3).Replace('\','/'))%(FileName)%(Extension)</LogicalName>
        </EmbeddedResource>
    </ItemGroup>

    <PropertyGroup>
        <NoWarn>$(NoWarn);CA1707</NoWarn>
    </PropertyGroup>
</Project>