<Project Sdk="Dalamud.NET.Sdk/15.0.0">
    <PropertyGroup>
        <OutputPath>dist</OutputPath>
        <PathMap Condition="$(SolutionDir) != ''">$(SolutionDir)=X:\</PathMap>
        <Platforms>x64</Platforms>
    </PropertyGroup>
    <ItemGroup>
      <PackageReference Update="DotNet.ReproducibleBuilds" Version="2.0.5" />
    </ItemGroup>
</Project>
