<Project Sdk="Dalamud.NET.Sdk/15.0.0">
    <PropertyGroup>
        <OutputPath>dist</OutputPath>
        <PathMap Condition="$(SolutionDir) != ''">$(SolutionDir)=X:\</PathMap>
        <Platforms>x64</Platforms>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\LLib\LLib.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Update="DalamudPackager" Version="15.0.0" />
    </ItemGroup>

    <Import Project="..\LLib\LLib.targets" />
</Project>
