using System.Collections.Generic;
using Questionable.Model.Common.Converter;
namespace Questionable.Model.Questing.Converter;

public sealed class ActionConverter() : EnumConverter<EAction>(Values)
{
    private static readonly Dictionary<EAction, string> Values = new()
    {
        { EAction.Return, "Return" },
        { EAction.DutyAction1, "Duty Action I" },
        { EAction.DutyAction2, "Duty Action II" },
        { EAction.HeavySwing, "Heavy Swing" },
        { EAction.Bootshine, "Bootshine" },
        { EAction.TwinSnakes, "Twin Snakes" },
        { EAction.Demolish, "Demolish" },
        { EAction.DragonKick, "Dragon Kick" },
        { EAction.HeavyShot, "Heavy Shot" },
        { EAction.Cure, "Cure" },
        { EAction.Cure2, "Cure II" },
        { EAction.Eukrasia, "Eukrasia" },
        { EAction.Diagnosis, "Diagnosis" },
        { EAction.EukrasianDiagnosis, "Eukrasian Diagnosis" },
        { EAction.Esuna, "Esuna" },
        { EAction.Physick, "Physick" },
        { EAction.AspectedBenefic, "Aspected Benefic" },
        { EAction.FormShift, "Form Shift" },
        { EAction.FieryBreath, "Fiery Breath" },
        { EAction.BuffetSanuwa, "Buffet (Sanuwa)" },
        { EAction.BuffetGriffin, "Buffet (Griffin)" },
        { EAction.Trample, "Trample" },
        { EAction.Fumigate, "Fumigate" },
        { EAction.Roar, "Roar" },
        { EAction.Seed, "Seed" },
        { EAction.Inhale, "Inhale" },
        { EAction.SiphonSnout, "Siphon Snout" },
        { EAction.PeculiarLight, "Peculiar Light" },
        { EAction.Cannonfire, "Cannonfire" },
        { EAction.RedGulal, "Red Gulal" },
        { EAction.YellowGulal, "Yellow Gulal" },
        { EAction.BlueGulal, "Blue Gulal" },
        { EAction.ElectrixFlux, "Electric Flux" },
        { EAction.HopStep, "Hop-step" },
        { EAction.Hide, "Hide" },
        { EAction.FumaShuriken, "Fuma Shuriken" },
        { EAction.Katon, "Katon" },
        { EAction.Raiton, "Raiton" },
        { EAction.SlugShot, "Slug Shot" },
        { EAction.BosomBrook, "Bosom Brook" },
        { EAction.Souleater, "Souleater" },
        { EAction.Fire3, "Fire III" },
        { EAction.Adloquium, "Adloquium" },
        { EAction.WaterCannon, "Water Cannon" },
        { EAction.Wasshoi, "Wasshoi" },
        { EAction.ShroudedLuminescence, "Shrouded Luminescence" },
        { EAction.BigSneeze, "Big Sneeze" },
        { EAction.TrickstersTreat, "Trickster's Treat" },
        { EAction.TreatersTrick, "Treater's Trick" },
        { EAction.PruningPirouette, "Pruning Pirouette" },
        { EAction.RoaringEggscapade, "Roaring Eggscapade" },
        { EAction.TheSpriganator, "The Spriganator" },
        { EAction.FSHCast, "FSHCast" },
        { EAction.FSHQuit, "FSHQuit" },
        { EAction.Triangulate, "Triangulate" },
        { EAction.FieldMastery1, "Field Mastery I" },
        { EAction.FieldMastery2, "Field Mastery II" },
        { EAction.FieldMastery3, "Field Mastery III" },
        { EAction.Prospect, "Prospect" },
        { EAction.SharpVision1, "Sharp Vision I" },
        { EAction.SharpVision2, "Sharp Vision II" },
        { EAction.SharpVision3, "Sharp Vision III" },
        { EAction.CollectMiner, "Collect (Miner)" },
        { EAction.CollectBotanist, "Collect (Botanist)" },
        { EAction.Ten, "Ten" },
        { EAction.Ninjutsu, "Ninjutsu" },
        { EAction.Chi, "Chi" },
        { EAction.Jin, "Jin" },
        { EAction.RabbitMedium, "Rabbit Medium" },
        { EAction.LuckOfTheMountaineer, "Luck of the Mountaineer" },
        { EAction.LuckOfThePioneer, "Luck of the Pioneer" },
        { EAction.MagitekPulse, "Magitek Pulse" },
        { EAction.MagitekThunder, "Magitek Thunder" },
        { EAction.ScourMiner, "Scour (Miner)" },
        { EAction.MeticulousMiner, "Meticulous (Miner)" },
        { EAction.ScrutinyMiner, "Scrutiny (Miner)" },
        { EAction.ScourBotanist, "Scour (Botanist)" },
        { EAction.MeticulousBotanist, "Meticulous (Botanist)" },
        { EAction.ScrutinyBotanist, "Scrutiny (Botanist)" }
    };
}
